version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
#      - POSTGRES_USER=mtsouk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

# docker exec -it postgres psql -U postgres