// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package todos

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	DeleteTodo(ctx context.Context, id int32) error
	GetAllTodo(ctx context.Context) ([]Todo, error)
	GetTodo(ctx context.Context, id int32) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
